{
 "title": "Clase",
 "description": "Cisco DNA Center Network Operations Center Dashboard. Added Eisenhower Executive Office Building to site health.",
 "time": { "from": "2020-09-23T21:22:42.000Z", "to": "2020-09-23T21:22:42.000Z" },
 "panels": [
  {
   "title": "NOTA TOTAL LABORATORIO",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time_sec,\n  Student_ID as metric,\n  Lab_total_ordinaria as value\nFROM Asignatura.Clase\nORDER BY Student_ID"
    }
   ]
  },
  {
   "title": "NOTA SOCRATIVES",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time_sec,\n  Student_ID as metric,\n  Socratives as value\nFROM Asignatura.Clase\nORDER BY Student_ID"
    }
   ]
  },
  {
   "title": "T0+T1+T3",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time_sec,\n  Student_ID as metric,\n  T0+T1+T2 as value\nFROM Asignatura.Clase\nORDER BY Student_ID"
    }
   ]
  },
  {
   "title": "RESULTADOS PEI",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time_sec,\n  Student_ID as metric,\n  pei as value\nFROM Asignatura.Clase\nORDER BY Student_ID"
    }
   ]
  },
  {
   "title": "NOTA FINAL ORDINARIA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time_sec,\n  Student_ID as metric,\n  Nota_final_ordinaria as value\nFROM Asignatura.Clase\nORDER BY Student_ID"
    }
   ]
  }
 ]
}