apiVersion: 1

datasources:
  - name: GrupoE
    type: mysql
    url: mariadb:3306
    database: EC
    user: root
    orgId: 1
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: ${GRAFANA_MYSQL_PASSWORD}
